/*
 * Swagger Shop rsschool
 * This is a swagger file for task3 rsschool nodejs-aws course.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: boltrukanisvlad@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Product', 'api/ProductServiceApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Product'), require('./api/ProductServiceApi'));
  }
}(function(ApiClient, Product, ProductServiceApi) {
  'use strict';

  /**
   * This_is_a_swagger_file_for_task3_rsschool_nodejs_aws_course_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var SwaggerShopRsschool = require('index'); // See note below*.
   * var xxxSvc = new SwaggerShopRsschool.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new SwaggerShopRsschool.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new SwaggerShopRsschool.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new SwaggerShopRsschool.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Product model constructor.
     * @property {module:model/Product}
     */
    Product: Product,
    /**
     * The ProductServiceApi service constructor.
     * @property {module:api/ProductServiceApi}
     */
    ProductServiceApi: ProductServiceApi
  };

  return exports;
}));
